#!/bin/sh
echo "============================================"
echo "  Demo App Running Successfully!"
echo "============================================"
echo ""
echo "This container was built by a GitHub Actions"
echo "runner on DigitalOcean Kubernetes (DOKS)"
echo "using Docker-in-Docker (DinD) mode."
echo ""
echo "Build timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "Hostname: $(hostname)"
echo ""
echo "Your existing Docker workflows work without"
echo "modification on this platform."
echo ""
